version: '3.6'

services:
  api:
    build: ./
    command: ["./app/apiserver", "-config-path", "app/configs/server.toml"]
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:12.0
    volumes:
      - ./data/pgdata/:/pgdata/
    ports:
      - 5432:5432
    env_file:
      - ./.env

